export default Object.freeze({
  APP: "App",
  SHOPPING: "Shopping",
  CATEGORY_SHOPPING: "CategoryShopping",
  SEARCH_RESULTS: "SearchResults",
  CATEGORYSHOPPING_RESULTS: "CategoryShoppingResults",
  STORE_MAIN: "StoreMain",
  ACCOUNT: "Account",
  MYACCOUNT: "MyAccount",
  STORESINFO_EDIT: "StoresInfoEdit",
  STORESMENU_EDIT: "StoresMenuEdit",
  AUTH: "Auth",
  WELCOME: "Welcome",
  LOGIN: "Login",
  REGISTER: "Register",
});
