export default Object.freeze({
  LOGINREGISTER2: "LoginRegister2",
  LOGINREGISTER1: "LoginRegister1",
  MAIN: "Main",
  STORE_DETAILS: "StoreDetails",
  CATEGORY_SHOPPING: "CategoryShopping",
  SEARCH_RESULTS: "SearchResults",
  SHOPPING2: "Shopping2",
  SHOPPING1: "Shopping1",
  LISTING_DETAILS: "ListingDetails",
  LISTINGS: "Listings",
  ACCOUNT: "Account",
  MESSAGES: "Messages",
  WELCOME: "Welcome",
});
