export default Object.freeze({
  APP: "App",
  SHOPPING: "Shopping",
  CATEGORY_SHOPPING: "CategoryShopping",
  SEARCH_RESULTS: "SearchResults",
  CATEGORYSHOPPING_RESULTS: "CategoryShoppingResults",
  STORE_MAIN: "StoreMain",
  ACCOUNT: "Account",
  MYACCOUNT: "MyAccount",
  ACCOUNTEDIT: "AccountEdit",
  STORES_IN_NEED: "StoresInNeed",
  STORESINFO_ADD: "StoresInfoAdd",
  STORESMENU_ADD: "StoresMenuAdd",
  AUTH: "Auth",
  WELCOME: "Welcome",
  LOGIN: "Login",
  REGISTER: "Register",
});
